---
namespace: simeononsecurity
name: "linux_update"
description: "Role to automate Linux security patching."
readme: README.md
version: 1.0.2
homepage: https://simeononsecurity.com/guides/automate-linux-patching-and-updates-with-ansible/
issues: https://github.com/simeononsecurity/ansible_linux_update/issues
repository: https://github.com/simeononsecurity/ansible_linux_update
authors:
  - SimeonOnSecurity (https://simeononsecurity.com)
license_file: LICENSE
tags:
- role
- linux
build_ignore:
- .github
- .gitattributes
- .gitignore
- .vscode
